source ~/robot_ws/install/local_setup.bash
source ~/robot_ws/install/local_setup.bash
source ~/robot_ws/install/local_setup.bash
source ~/robot_ws/install/local_setup.bash
source ~/robot_ws/install/local_setup.bash
source ~/robot_ws/install/local_setup.bash
source ~/robot_ws/install/local_setup.bash
source ~/robot_ws/install/local_setup.bash
source ~/robot_ws/install/local_setup.bash
